# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 18:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='teamID',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='userID',
        ),
        migrations.AddField(
            model_name='team',
            name='bet_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='desc',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.DeleteModel(
            name='Bet',
        ),
    ]
