# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20161124_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='bet_users',
            new_name='betUsers',
        ),
        migrations.AddField(
            model_name='team',
            name='imageUrl',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
